### ISSUE TITLE
专业版可否用此api？

### ISSUE THREAD

**Issue by gscfwid** [jinshuju/jinshuju-api-docs#4]
我的client_id填什么？

**Comment by mechiland** [comment]
专业版适用的[个人版API(账户位于jinshuju.net)](https://github.com/jinshuju/jinshuju-api-docs/blob/master/personal-api.md)

client_id 目前并未向所有人开放。如需要，请向 marketing@jinshuju.net 发起申请，注明用途

**Comment by gscfwid** [comment]
我问了下客服说可以用v1版的api，请问get请求的header要怎么填写，url是多少？网上搜不到，谢谢

**Comment by gscfwid** [comment]
搞定了，利用HTTP basic认证
